site_name: 30 Days Javascript
repo_url: https://github.com/devinesia/30-days-javascript-web
edit_uri: edit/main/docs/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  favicon: images/javascript.png
  logo: images/javascript.png
  name: material
  palette:
    primary: amber
plugins:
  - search
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: id
          name: Bahasa Indonesia
          build: true